version: '3'
services:
  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/public
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
  php-fpm:
    build: ./php-fpm
    restart: always
    volumes:
      - ./src:/var/www/public
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini


